### ISSUE TITLE
Enable travis builds

### ISSUE THREAD

**Issue by joshday** [Hua-Zhou/SnpArrays.jl#1]
Now that SnpArrays is open source, travis builds should be added.  @Hua-Zhou since you have ownership, you can sign into http://travis-ci.org with your github account and enable builds.

**Comment by Hua-Zhou** [comment]
Done. Though the test scripts need to updated to reflect recent changes in the implementation for SnpArrays.

**Comment by joshday** [comment]
Cool.  I see you also enabled codecov in travis.yml.  You may as also want to add that badge for the README.  

Also, I edited travis.yml to allow failures on the nightly builds so the badge still stays green if 0.4 builds succeed but nightly builds fail.

**Comment by Hua-Zhou** [comment]
Added badge for the README. Thanks for tweaks about the nightly builds.
